import tempfile
import unittest
from pathlib import Path

from spirosim import versioning


class VersioningTests(unittest.TestCase):
    def test_resolve_version_defaults(self) -> None:
        info = versioning.resolve_version({})
        self.assertEqual(info.version, "0.0.0-dev")
        self.assertEqual(info.sha, "unknown")

    def test_version_file_contents(self) -> None:
        contents = versioning.version_file_contents("1.2.3", "abc123")
        expected = "\n".join(
            [
                "# Generated by CI - do not edit by hand.",
                "__version__ = '1.2.3'",
                "__version_sha__ = 'abc123'",
                "",
            ]
        )
        self.assertEqual(contents, expected)

    def test_write_version_file(self) -> None:
        with tempfile.TemporaryDirectory() as temp_dir:
            path = Path(temp_dir) / "_version.py"
            versioning.write_version_file(path, "2.0.0", "deadbee")
            self.assertTrue(path.exists())
            self.assertIn("__version__ = '2.0.0'", path.read_text(encoding="utf-8"))


if __name__ == "__main__":
    unittest.main()
