"""Version metadata helpers for CI and local tooling."""

from __future__ import annotations

from dataclasses import dataclass
import os
from pathlib import Path
from typing import Mapping


@dataclass(frozen=True)
class VersionInfo:
    """Resolved version information."""

    version: str
    sha: str


def resolve_version(env: Mapping[str, str] | None = None) -> VersionInfo:
    """Resolve version information from environment-like mapping."""

    environment = env if env is not None else os.environ
    version = environment.get("SEMVER") or "0.0.0-dev"
    sha = environment.get("SHA") or "unknown"
    return VersionInfo(version=version, sha=sha)


def version_file_contents(version: str, sha: str) -> str:
    """Generate the contents of the version metadata file."""

    return "\n".join(
        [
            "# Generated by CI - do not edit by hand.",
            f"__version__ = {version!r}",
            f"__version_sha__ = {sha!r}",
            "",
        ]
    )


def write_version_file(path: Path, version: str, sha: str) -> None:
    """Write the version metadata file to disk."""

    path.write_text(version_file_contents(version, sha), encoding="utf-8")
